# Generated by Django 3.0.3 on 2020-07-05 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=64)),
                ('job', models.CharField(max_length=64)),
                ('job_link', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
                ('frequency', models.CharField(max_length=64)),
                ('salary', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '实习',
                'verbose_name_plural': '实习',
                'ordering': ['index'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_time',
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='interns',
            field=models.ManyToManyField(blank=True, to='login.Interns'),
        ),
    ]
