# Generated by Django 3.0.3 on 2020-07-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200705_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '研究助理',
                'verbose_name_plural': '研究助理',
                'ordering': ['index'],
            },
        ),
        migrations.AlterField(
            model_name='interns',
            name='company_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='interns',
            name='job',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='interns',
            name='job_link',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='ras',
            field=models.ManyToManyField(blank=True, to='login.RAs'),
        ),
    ]
