# Generated by Django 3.0.8 on 2020-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200705_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_name', models.CharField(max_length=128, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('forum', models.ManyToManyField(blank=True, to='login.Forum')),
            ],
        ),
    ]
